package providers

const (
	ErrorCodeMissingCredential               = "missing_credential"
	ErrorCodeCredentialExpired               = "credential_expired"
	ErrorCodeMissingRefreshCredential        = "missing_refresh_credential"
	ErrorCodeCredentialRefreshNotSupported   = "credential_refresh_not_supported"
	ErrorCodeCredentialStateUpdateFailed     = "credential_state_update_failed"
	ErrorCodeGatewayAPIKeyDisabled           = "gateway_api_key_disabled"
	ErrorCodeUpstreamAuthError               = "upstream_auth_error"
	ErrorCodeUpstreamEmptyResponse           = "upstream_empty_response"
	ErrorCodeUpstreamForbidden               = "upstream_forbidden"
	ErrorCodeUpstreamInvalidJSON             = "upstream_invalid_json"
	ErrorCodeUpstreamInvalidStreamChunk      = "upstream_invalid_stream_chunk"
	ErrorCodeUpstreamNotFound                = "upstream_not_found"
	ErrorCodeUpstreamProviderBanned          = "upstream_provider_banned"
	ErrorCodeUpstreamRateLimited             = "upstream_rate_limited"
	ErrorCodeUpstreamReadError               = "upstream_read_error"
	ErrorCodeUpstreamRejected                = "upstream_rejected"
	ErrorCodeUpstreamRequestBuildFailed      = "upstream_request_build_failed"
	ErrorCodeUpstreamServerError             = "upstream_server_error"
	ErrorCodeUpstreamTemporarilyUnavailable  = "upstream_temporarily_unavailable"
	ErrorCodeUpstreamTransportError          = "upstream_transport_error"
	ErrorCodeImageBackendRequiresOAuth       = "image_backend_requires_oauth"
	ErrorCodeImageEndpointUnsupported        = "image_endpoint_unsupported"
	ErrorCodeImageGenerationFailed           = "image_generation_failed"
	ErrorCodeImageGenerationNotStarted       = "image_generation_not_started"
	ErrorCodeImageGenerationRejected         = "image_generation_rejected"
	ErrorCodeImageModelUnsupported           = "image_model_unsupported"
	ErrorCodeImagePollTimeout                = "image_poll_timeout"
	ErrorCodeImageUploadEmpty                = "image_upload_empty"
	ErrorCodeChatGPTArkoseRequired           = "chatgpt_arkose_required"
	ErrorCodeChatGPTConduitTokenMissing      = "chatgpt_conduit_token_missing"
	ErrorCodeChatGPTProofTokenFailed         = "chatgpt_proof_token_failed"
	ErrorCodeChatGPTRequirementsMissingToken = "chatgpt_requirements_missing_token"
	ErrorCodeChatGPTUploadURLMissing         = "chatgpt_upload_url_missing"
)
