package failover

const (
	AttemptStatusAudioMultipartUnsupported        = "audio_multipart_unsupported"
	AttemptStatusAudioSpeechUnsupported           = "audio_speech_unsupported"
	AttemptStatusBoundAccountUnavailable          = "bound_account_unavailable"
	AttemptStatusEmbeddingUnsupported             = "embedding_unsupported"
	AttemptStatusImageGenerationStreamUnsupported = "image_generation_stream_unsupported"
	AttemptStatusImageGenerationUnsupported       = "image_generation_unsupported"
	AttemptStatusImageMultipartStreamUnsupported  = "image_multipart_stream_unsupported"
	AttemptStatusImageMultipartUnsupported        = "image_multipart_unsupported"
	AttemptStatusModerationUnsupported            = "moderation_unsupported"
	AttemptStatusNoAccount                        = "no_account"
	AttemptStatusNoAdapter                        = "no_adapter"
	AttemptStatusResponsesStreamUnsupported       = "responses_stream_unsupported"
	AttemptStatusResponsesUnsupported             = "responses_unsupported"
	AttemptStatusResponsesWebSocketUnsupported    = "responses_websocket_unsupported"
	AttemptStatusStreamUnsupported                = "stream_unsupported"
	AttemptStatusTokenCountUnsupported            = "token_count_unsupported"
	ErrorCodeAudioMultipartNotSupported           = "audio_multipart_not_supported"
	ErrorCodeAudioSpeechNotSupported              = "audio_speech_not_supported"
	ErrorCodeBoundAccountUnavailable              = "bound_account_unavailable"
	ErrorCodeEmbeddingsNotSupported               = "embeddings_not_supported"
	ErrorCodeImageGenerationNotSupported          = "image_generation_not_supported"
	ErrorCodeImageGenerationStreamingNotSupported = "image_generation_streaming_not_supported"
	ErrorCodeImageMultipartNotSupported           = "image_multipart_not_supported"
	ErrorCodeImageMultipartStreamingNotSupported  = "image_multipart_streaming_not_supported"
	ErrorCodeModerationsNotSupported              = "moderations_not_supported"
	ErrorCodeNoAccount                            = "no_account"
	ErrorCodeNoAdapter                            = "no_adapter"
	ErrorCodeResponsesNotSupported                = "responses_not_supported"
	ErrorCodeResponsesStreamingNotSupported       = "responses_streaming_not_supported"
	ErrorCodeResponsesWebSocketNotSupported       = "responses_websocket_not_supported"
	ErrorCodeStreamingNotSupported                = "streaming_not_supported"
	ErrorCodeTokenCountNotSupported               = "token_count_not_supported"
)
